// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/gateways/gitcommand/gitcommand.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/cloudnativedaysjp/reviewapp-operator/api/v1alpha1"
	models "github.com/cloudnativedaysjp/reviewapp-operator/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockGitLocalRepoIface is a mock of GitLocalRepoIface interface.
type MockGitLocalRepoIface struct {
	ctrl     *gomock.Controller
	recorder *MockGitLocalRepoIfaceMockRecorder
}

// MockGitLocalRepoIfaceMockRecorder is the mock recorder for MockGitLocalRepoIface.
type MockGitLocalRepoIfaceMockRecorder struct {
	mock *MockGitLocalRepoIface
}

// NewMockGitLocalRepoIface creates a new mock instance.
func NewMockGitLocalRepoIface(ctrl *gomock.Controller) *MockGitLocalRepoIface {
	mock := &MockGitLocalRepoIface{ctrl: ctrl}
	mock.recorder = &MockGitLocalRepoIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitLocalRepoIface) EXPECT() *MockGitLocalRepoIfaceMockRecorder {
	return m.recorder
}

// CommitAndPush mocks base method.
func (m *MockGitLocalRepoIface) CommitAndPush(ctx context.Context, gp models.InfraRepoLocalDir, message string) (*models.InfraRepoLocalDir, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitAndPush", ctx, gp, message)
	ret0, _ := ret[0].(*models.InfraRepoLocalDir)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitAndPush indicates an expected call of CommitAndPush.
func (mr *MockGitLocalRepoIfaceMockRecorder) CommitAndPush(ctx, gp, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitAndPush", reflect.TypeOf((*MockGitLocalRepoIface)(nil).CommitAndPush), ctx, gp, message)
}

// CreateFiles mocks base method.
func (m *MockGitLocalRepoIface) CreateFiles(arg0 context.Context, arg1 models.InfraRepoLocalDir, arg2 ...models.File) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateFiles", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFiles indicates an expected call of CreateFiles.
func (mr *MockGitLocalRepoIfaceMockRecorder) CreateFiles(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFiles", reflect.TypeOf((*MockGitLocalRepoIface)(nil).CreateFiles), varargs...)
}

// DeleteFiles mocks base method.
func (m *MockGitLocalRepoIface) DeleteFiles(arg0 context.Context, arg1 models.InfraRepoLocalDir, arg2 ...models.File) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFiles", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFiles indicates an expected call of DeleteFiles.
func (mr *MockGitLocalRepoIfaceMockRecorder) DeleteFiles(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFiles", reflect.TypeOf((*MockGitLocalRepoIface)(nil).DeleteFiles), varargs...)
}

// ForceClone mocks base method.
func (m *MockGitLocalRepoIface) ForceClone(arg0 context.Context, arg1 v1alpha1.ReviewAppCommonSpecInfraTarget) (models.InfraRepoLocalDir, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceClone", arg0, arg1)
	ret0, _ := ret[0].(models.InfraRepoLocalDir)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForceClone indicates an expected call of ForceClone.
func (mr *MockGitLocalRepoIfaceMockRecorder) ForceClone(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceClone", reflect.TypeOf((*MockGitLocalRepoIface)(nil).ForceClone), arg0, arg1)
}

// WithCredential mocks base method.
func (m *MockGitLocalRepoIface) WithCredential(credential models.GitCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCredential", credential)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithCredential indicates an expected call of WithCredential.
func (mr *MockGitLocalRepoIfaceMockRecorder) WithCredential(credential interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCredential", reflect.TypeOf((*MockGitLocalRepoIface)(nil).WithCredential), credential)
}
