# permissions for end users to edit jobtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobtemplate-editor-role
rules:
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - jobtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - jobtemplates/status
  verbs:
  - get
