# permissions for end users to view manifeststemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manifeststemplate-viewer-role
rules:
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - manifeststemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - manifeststemplates/status
  verbs:
  - get
