# permissions for end users to edit manifeststemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manifeststemplate-editor-role
rules:
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - manifeststemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - manifeststemplates/status
  verbs:
  - get
