# permissions for end users to view pullrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pullrequest-viewer-role
rules:
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - pullrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - pullrequests/status
  verbs:
  - get
