# permissions for end users to edit pullrequestcaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pullrequestcache-editor-role
rules:
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - pullrequestcaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - pullrequestcaches/status
  verbs:
  - get
