# permissions for end users to edit pullrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pullrequest-editor-role
rules:
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - pullrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - pullrequests/status
  verbs:
  - get
