# permissions for end users to view reviewappinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reviewappinstance-viewer-role
rules:
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - reviewappinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - reviewappinstances/status
  verbs:
  - get
