
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - reviewappinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - reviewappinstances/finalizers
  verbs:
  - update
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - reviewappinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - reviewapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - reviewapps/finalizers
  verbs:
  - update
- apiGroups:
  - dreamkast.cloudnativedays.jp
  resources:
  - reviewapps/status
  verbs:
  - get
  - patch
  - update
