# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: manifeststemplates.dreamkast.cloudnativedays.jp
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: reviewapp-system
          name: webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
