apiVersion: dreamkast.cloudnativedays.jp/v1beta1
kind: ReviewApp
metadata:
  name: reviewapp-sample
spec:
  app:
    repository: https://github.com/ShotaKitazawa/reviewapp-operator-demo-app
    gitSecretRef:
      name: git-creds
      key: token
    ignoreLabels: []
    ignoreTitleExp: '^\[dreamkast-releasebot\]'
  infra:
    repository: https://github.com/ShotaKitazawa/reviewapp-operator-demo-infra
    gitSecretRef:
      name: git-creds
      key: token
    manifests:
      templatesName:
        - manifeststemplate-sample
      dirpath: "ovarlays/dev/{{.variables.app_repository_alias}}-{{.pull_request.number}}"
    argocdApp:
      templateName: applicationtemplate-sample
      filepath: ".app/dev/{{.variables.app_repository_alias}}-{{.pull_request.number}}.yaml"
  variables:
    - app_repository_alias=sample

