apiVersion: dreamkast.cloudnativedays.jp/v1alpha1
kind: ReviewAppManager
metadata:
  name: reviewapp-sample
spec:
  appRepoTarget:
    username: ShotaKitazawa
    organization: ShotaKitazawa
    repository: reviewapp-operator-demo-app
    gitSecretRef:
      name: git-creds
      key: token
    ignoreLabels: []
    ignoreTitleExp: '^\[dreamkast-releasebot\]'
  appRepoConfig:
    message: |
      # title

      **message**

      * list
      * {{.AppRepo.Organization}}
      * {{.AppRepo.Repository}}
      * {{.AppRepo.PrNumber}}
      * {{.AppRepo.LatestCommitSha}}
      * {{.InfraRepo.Organization}}
      * {{.InfraRepo.Repository}}
      * {{.Variables.AppRepositoryAlias}}
      * {{.Variables.dummy}}
  infraRepoTarget:
    username: ShotaKitazawa
    organization: ShotaKitazawa
    repository: reviewapp-operator-demo-infra
    branch: master
    gitSecretRef:
      name: git-creds
      key: token
  infraRepoConfig:
    manifests:
      templates:
        - namespace: argocd
          name: manifeststemplate-sample
      dirpath: "overlays/dev/{{.Variables.AppRepositoryAlias}}-{{.AppRepo.PrNumber}}"
    argocdApp:
      template:
        namespace: argocd
        name: applicationtemplate-sample
      filepath: ".apps/dev/{{.Variables.AppRepositoryAlias}}-{{.AppRepo.PrNumber}}.yaml"
  preStopJob:
    namespace: argocd
    name: jobtemplate-sample
  variables:
    - AppRepositoryAlias=sample

