apiVersion: dreamkast.cloudnativedays.jp/v1beta1
kind: ManifestsTemplate
metadata:
  name: manifeststemplate-sample
data:
  kustomization.yaml: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    bases:
    - ../../base
