//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationTemplate) DeepCopyInto(out *ApplicationTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationTemplate.
func (in *ApplicationTemplate) DeepCopy() *ApplicationTemplate {
	if in == nil {
		return nil
	}
	out := new(ApplicationTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationTemplateList) DeepCopyInto(out *ApplicationTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationTemplateList.
func (in *ApplicationTemplateList) DeepCopy() *ApplicationTemplateList {
	if in == nil {
		return nil
	}
	out := new(ApplicationTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationTemplateSpec) DeepCopyInto(out *ApplicationTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationTemplateSpec.
func (in *ApplicationTemplateSpec) DeepCopy() *ApplicationTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobTemplate) DeepCopyInto(out *JobTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobTemplate.
func (in *JobTemplate) DeepCopy() *JobTemplate {
	if in == nil {
		return nil
	}
	out := new(JobTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JobTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobTemplateList) DeepCopyInto(out *JobTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JobTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobTemplateList.
func (in *JobTemplateList) DeepCopy() *JobTemplateList {
	if in == nil {
		return nil
	}
	out := new(JobTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JobTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobTemplateSpec) DeepCopyInto(out *JobTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobTemplateSpec.
func (in *JobTemplateSpec) DeepCopy() *JobTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(JobTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Manifests) DeepCopyInto(out *Manifests) {
	{
		in := &in
		*out = make(Manifests, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Manifests.
func (in Manifests) DeepCopy() Manifests {
	if in == nil {
		return nil
	}
	out := new(Manifests)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ManifestsBase64) DeepCopyInto(out *ManifestsBase64) {
	{
		in := &in
		*out = make(ManifestsBase64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestsBase64.
func (in ManifestsBase64) DeepCopy() ManifestsBase64 {
	if in == nil {
		return nil
	}
	out := new(ManifestsBase64)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestsCache) DeepCopyInto(out *ManifestsCache) {
	*out = *in
	if in.ManifestsBase64 != nil {
		in, out := &in.ManifestsBase64, &out.ManifestsBase64
		*out = make(ManifestsBase64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestsCache.
func (in *ManifestsCache) DeepCopy() *ManifestsCache {
	if in == nil {
		return nil
	}
	out := new(ManifestsCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestsTemplate) DeepCopyInto(out *ManifestsTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestsTemplate.
func (in *ManifestsTemplate) DeepCopy() *ManifestsTemplate {
	if in == nil {
		return nil
	}
	out := new(ManifestsTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestsTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestsTemplateList) DeepCopyInto(out *ManifestsTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManifestsTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestsTemplateList.
func (in *ManifestsTemplateList) DeepCopy() *ManifestsTemplateList {
	if in == nil {
		return nil
	}
	out := new(ManifestsTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestsTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestsTemplateSpec) DeepCopyInto(out *ManifestsTemplateSpec) {
	*out = *in
	if in.CandidateData != nil {
		in, out := &in.CandidateData, &out.CandidateData
		*out = make(Manifests, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.StableData != nil {
		in, out := &in.StableData, &out.StableData
		*out = make(Manifests, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestsTemplateSpec.
func (in *ManifestsTemplateSpec) DeepCopy() *ManifestsTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ManifestsTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequest) DeepCopyInto(out *PullRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequest.
func (in *PullRequest) DeepCopy() *PullRequest {
	if in == nil {
		return nil
	}
	out := new(PullRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PullRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestList) DeepCopyInto(out *PullRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PullRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestList.
func (in *PullRequestList) DeepCopy() *PullRequestList {
	if in == nil {
		return nil
	}
	out := new(PullRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PullRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestSpec) DeepCopyInto(out *PullRequestSpec) {
	*out = *in
	in.AppTarget.DeepCopyInto(&out.AppTarget)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestSpec.
func (in *PullRequestSpec) DeepCopy() *PullRequestSpec {
	if in == nil {
		return nil
	}
	out := new(PullRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestStatus) DeepCopyInto(out *PullRequestStatus) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestStatus.
func (in *PullRequestStatus) DeepCopy() *PullRequestStatus {
	if in == nil {
		return nil
	}
	out := new(PullRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewApp) DeepCopyInto(out *ReviewApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewApp.
func (in *ReviewApp) DeepCopy() *ReviewApp {
	if in == nil {
		return nil
	}
	out := new(ReviewApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReviewApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppCommonSpec) DeepCopyInto(out *ReviewAppCommonSpec) {
	*out = *in
	in.AppTarget.DeepCopyInto(&out.AppTarget)
	out.AppConfig = in.AppConfig
	in.InfraTarget.DeepCopyInto(&out.InfraTarget)
	in.InfraConfig.DeepCopyInto(&out.InfraConfig)
	out.PreStopJob = in.PreStopJob
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppCommonSpec.
func (in *ReviewAppCommonSpec) DeepCopy() *ReviewAppCommonSpec {
	if in == nil {
		return nil
	}
	out := new(ReviewAppCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppCommonSpecAppConfig) DeepCopyInto(out *ReviewAppCommonSpecAppConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppCommonSpecAppConfig.
func (in *ReviewAppCommonSpecAppConfig) DeepCopy() *ReviewAppCommonSpecAppConfig {
	if in == nil {
		return nil
	}
	out := new(ReviewAppCommonSpecAppConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppCommonSpecAppTarget) DeepCopyInto(out *ReviewAppCommonSpecAppTarget) {
	*out = *in
	if in.GitSecretRef != nil {
		in, out := &in.GitSecretRef, &out.GitSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.IgnoreLabels != nil {
		in, out := &in.IgnoreLabels, &out.IgnoreLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppCommonSpecAppTarget.
func (in *ReviewAppCommonSpecAppTarget) DeepCopy() *ReviewAppCommonSpecAppTarget {
	if in == nil {
		return nil
	}
	out := new(ReviewAppCommonSpecAppTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppCommonSpecInfraArgoCDApp) DeepCopyInto(out *ReviewAppCommonSpecInfraArgoCDApp) {
	*out = *in
	out.Template = in.Template
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppCommonSpecInfraArgoCDApp.
func (in *ReviewAppCommonSpecInfraArgoCDApp) DeepCopy() *ReviewAppCommonSpecInfraArgoCDApp {
	if in == nil {
		return nil
	}
	out := new(ReviewAppCommonSpecInfraArgoCDApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppCommonSpecInfraConfig) DeepCopyInto(out *ReviewAppCommonSpecInfraConfig) {
	*out = *in
	in.Manifests.DeepCopyInto(&out.Manifests)
	out.ArgoCDApp = in.ArgoCDApp
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppCommonSpecInfraConfig.
func (in *ReviewAppCommonSpecInfraConfig) DeepCopy() *ReviewAppCommonSpecInfraConfig {
	if in == nil {
		return nil
	}
	out := new(ReviewAppCommonSpecInfraConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppCommonSpecInfraManifests) DeepCopyInto(out *ReviewAppCommonSpecInfraManifests) {
	*out = *in
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]NamespacedName, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppCommonSpecInfraManifests.
func (in *ReviewAppCommonSpecInfraManifests) DeepCopy() *ReviewAppCommonSpecInfraManifests {
	if in == nil {
		return nil
	}
	out := new(ReviewAppCommonSpecInfraManifests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppCommonSpecInfraTarget) DeepCopyInto(out *ReviewAppCommonSpecInfraTarget) {
	*out = *in
	if in.GitSecretRef != nil {
		in, out := &in.GitSecretRef, &out.GitSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppCommonSpecInfraTarget.
func (in *ReviewAppCommonSpecInfraTarget) DeepCopy() *ReviewAppCommonSpecInfraTarget {
	if in == nil {
		return nil
	}
	out := new(ReviewAppCommonSpecInfraTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppList) DeepCopyInto(out *ReviewAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReviewApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppList.
func (in *ReviewAppList) DeepCopy() *ReviewAppList {
	if in == nil {
		return nil
	}
	out := new(ReviewAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReviewAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppManager) DeepCopyInto(out *ReviewAppManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppManager.
func (in *ReviewAppManager) DeepCopy() *ReviewAppManager {
	if in == nil {
		return nil
	}
	out := new(ReviewAppManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReviewAppManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppManagerList) DeepCopyInto(out *ReviewAppManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReviewAppManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppManagerList.
func (in *ReviewAppManagerList) DeepCopy() *ReviewAppManagerList {
	if in == nil {
		return nil
	}
	out := new(ReviewAppManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReviewAppManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppManagerSpec) DeepCopyInto(out *ReviewAppManagerSpec) {
	*out = *in
	in.ReviewAppCommonSpec.DeepCopyInto(&out.ReviewAppCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppManagerSpec.
func (in *ReviewAppManagerSpec) DeepCopy() *ReviewAppManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ReviewAppManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppSpec) DeepCopyInto(out *ReviewAppSpec) {
	*out = *in
	in.ReviewAppCommonSpec.DeepCopyInto(&out.ReviewAppCommonSpec)
	out.PullRequest = in.PullRequest
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppSpec.
func (in *ReviewAppSpec) DeepCopy() *ReviewAppSpec {
	if in == nil {
		return nil
	}
	out := new(ReviewAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppStatus) DeepCopyInto(out *ReviewAppStatus) {
	*out = *in
	out.Sync = in.Sync
	in.PullRequestCache.DeepCopyInto(&out.PullRequestCache)
	in.ManifestsCache.DeepCopyInto(&out.ManifestsCache)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppStatus.
func (in *ReviewAppStatus) DeepCopy() *ReviewAppStatus {
	if in == nil {
		return nil
	}
	out := new(ReviewAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppStatusPullRequestCache) DeepCopyInto(out *ReviewAppStatusPullRequestCache) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.SyncedTimestamp.DeepCopyInto(&out.SyncedTimestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppStatusPullRequestCache.
func (in *ReviewAppStatusPullRequestCache) DeepCopy() *ReviewAppStatusPullRequestCache {
	if in == nil {
		return nil
	}
	out := new(ReviewAppStatusPullRequestCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewAppStatusSync) DeepCopyInto(out *ReviewAppStatusSync) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewAppStatusSync.
func (in *ReviewAppStatusSync) DeepCopy() *ReviewAppStatusSync {
	if in == nil {
		return nil
	}
	out := new(ReviewAppStatusSync)
	in.DeepCopyInto(out)
	return out
}
