// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/cloudnativedaysjp/reviewapp-operator/domain/services"
	"github.com/cloudnativedaysjp/reviewapp-operator/gateways/gitcommand"
	"github.com/cloudnativedaysjp/reviewapp-operator/gateways/githubapi"
	"github.com/go-logr/logr"
)

// Injectors from wire.go:

func NewGitRemoteRepoAppService(l logr.Logger) (*services.GitRemoteRepoAppService, error) {
	gitHubApiGateway := githubapi.NewGitHubApiGateway(l)
	gitRemoteRepoAppService := services.NewGitRemoteRepoAppService(gitHubApiGateway, l)
	return gitRemoteRepoAppService, nil
}

func NewGitRemoteRepoInfraService(l logr.Logger) (*services.GitRemoteRepoInfraService, error) {
	gitCommandGateway, err := gitcommand.NewGitCommandGateway(l)
	if err != nil {
		return nil, err
	}
	gitRemoteRepoInfraService := services.NewGitRemoteRepoInfraService(gitCommandGateway, l)
	return gitRemoteRepoInfraService, nil
}
