name: Push a new tag when labeled PR was merged

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: imranismail/setup-kustomize@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: set image to kustomization.yaml
        run: |
          cd config/default/
          kustomize edit set image public.ecr.aws/f5j9d0q5/reviewapp-operator:${{ steps.bump-semver.outputs.new_version }}

      - name: create install.yaml
        run: |
          kustomize build config/crd/ > install.yaml
          echo "---" >> install.yaml
          kustomize build config/default/ >> install.yaml

      - name: build reviewappctl
        run: |
          GOOS=linux GOARCH=amd64 go build -o reviewappctl-linux-amd64 cmd/reviewappctl/main.go
          GOOS=darwin GOARCH=amd64 go build -o reviewappctl-darwin-amd64 cmd/reviewappctl/main.go

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
          draft: false
          prerelease: false
          body: |
            # Quick Start

            ```
            kubectl create namespace reviewapp-operator-system
            kubectl apply -n reviewapp-operator-system -f https://github.com/cloudnativedaysjp/reviewapp-operator/releases/download/${{ steps.bump-semver.outputs.new_version }}/install.yaml
            ```
          files:
            - install.yaml
            - reviewappctl-darwin-amd64
            - reviewappctl-linux-amd64
