name: Push a new tag when labeled PR was merged

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: imranismail/setup-kustomize@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Setup variables
        id: variables
        run: echo "::set-output name=version::${GITHUB_REF##*/}"

      - name: Set image to kustomization.yaml
        run: |
          cd config/default/
          kustomize edit set image public.ecr.aws/f5j9d0q5/reviewapp-operator:${{ steps.variables.outputs.version }}

      - name: Create install.yaml
        run: |
          kustomize build config/crd/ > install.yaml
          echo "---" >> install.yaml
          kustomize build config/default/ >> install.yaml

      - name: Build reviewappctl
        run: |
          GOOS=linux GOARCH=amd64 go build -o reviewappctl-linux-amd64 cmd/reviewappctl/main.go
          GOOS=darwin GOARCH=amd64 go build -o reviewappctl-darwin-amd64 cmd/reviewappctl/main.go

     - name: Get sentence of Release Note from Pull Request
       uses: actions-ecosystem/action-regex-match@v2
       id: regex-match
       with:
         text: ${{ github.event.pull_request.body }}
         regex: '```release_note([\s\S]*)```'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.variables.outputs.version }}
          draft: false
          prerelease: false
          body: |
            # Quick Start

            ```
            kubectl create namespace reviewapp-operator-system
            kubectl apply -n reviewapp-operator-system -f https://github.com/cloudnativedaysjp/reviewapp-operator/releases/download/${{ steps.variables.outputs.version }}/install.yaml
            ```

            # Release Note

            ${{ steps.regex-match.outputs.group1 }}
          files:
            - install.yaml
            - reviewappctl-darwin-amd64
            - reviewappctl-linux-amd64
