name: Push a new tag when labeled PR was merged

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create install.yaml
        run: |
          cat << _EOL_ >> config/default/kustomization.yaml
          images:
          - name: public.ecr.aws/f5j9d0q5/reviewapp-operator
            newTag: ${{ steps.bump-semver.outputs.new_version }}
          _EOL_
          kustomize build config/crd/ > install.yaml
          echo "---" >> install.yaml
          kustomize build config/default/ >> install.yaml

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
          draft: false
          prerelease: false
          body: |
            # Quick Start

            ```
            kubectl create namespace reviewapp-operator-system
            kubectl apply -n reviewapp-operator-system -f https://github.com/cloudnativedaysjp/reviewapp-operator/releases/download/${{ steps.bump-semver.outputs.new_version }}/install.yaml
            ```
          files: install.yaml
