name: test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.8
      - name: unit test
        run: make unit-test

  integration-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: helm/kind-action@v1.2.0
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.8
      - name: integration test
        run: make integration-test
